Repository yobgob/too-many-hooks, pull requests merged in 2023-02, with the labels that each got.

#54 Add Action for commenting Chromatic output
  .github/workflows/chromatic.yml
  .github/workflows/lint-and-build-storybook.yml
  storybook/package.json
  storybook/yarn.lock
Labels: tooling

#48 Add `useThrottleFunction` and `useThrottleValue` hooks
  storybook/.storybook/main.cjs
  storybook/package.json
  storybook/src/common/assets/book-names.json
  storybook/src/common/assets/books.ts
  storybook/src/common/components/Button.tsx
  storybook/src/common/components/Modal.tsx
  storybook/src/common/components/Select.tsx
  storybook/src/common/components/index.ts
  storybook/src/stories/UseArray/Bookshelf/Bookshelf.tsx
  storybook/src/stories/UseArray/Bookshelf/constants.ts
  storybook/src/stories/UseArray/Burger/Burger.tsx
  storybook/src/stories/UseDeepCompareEffect.docs.mdx
  storybook/src/stories/UseDeepCompareEffect/API/API.tsx
  storybook/src/stories/UseDeepCompareEffect/UseDeepCompareEffect.stories.mdx
  storybook/src/stories/UseFlag/Form.tsx
  storybook/src/stories/UseFlag/Modal.tsx
  storybook/src/stories/UseTally/SocialMedia/SocialMedia.tsx
  storybook/src/stories/UseThrottleFunction/API/API.tsx
  storybook/src/stories/UseThrottleFunction/API/assets/countries.json
  storybook/src/stories/UseThrottleFunction/API/index.ts
  storybook/src/stories/UseThrottleFunction/UseThrottleFunction.stories.mdx
  storybook/src/stories/UseThrottleFunction/stories.tsx
  storybook/src/stories/UseThrottleValue/Counter/Counter.tsx
  storybook/src/stories/UseThrottleValue/Counter/index.ts
  storybook/src/stories/UseThrottleValue/Search.tsx
  storybook/src/stories/UseThrottleValue/UseThrottleValue.stories.mdx
  storybook/src/stories/UseThrottleValue/stories.tsx
  storybook/yarn.lock
  too-many-hooks/.eslintrc.cjs
  too-many-hooks/package.json
  too-many-hooks/src/index.ts
  too-many-hooks/src/useThrottleFunction.ts
  too-many-hooks/src/useThrottleValue.ts
  too-many-hooks/yarn.lock
Labels: enhancement

#57 Update README.md
  README.md
Labels: documentation

#59 Update contributing guide
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: documentation
